apiVersion: v1
kind: PersistentVolume
metadata:
  name: seafile-data-pv
  namespace: seafile-testing
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/kube/seafile-testing"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-data-pvc
  namespace: seafile-testing
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile
  namespace: seafile-testing  
spec:
  selector:
    matchLabels:
      app: seafile
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: seafile
    spec:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "memcached"
      containers:
        - image: mariadb:10.5
          name: seafile-mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "kodokijo"
            - name: MYSQL_LOG_CONSOLE
              value: "true"
          volumeMounts:
            - name: seafile-data-storage
              mountPath: /var/lib/mysql
              subPath: seafile-db
        - image: memcached:1.5.6
          name: seafile-memcached
          command: ["memcached"]
          args: ["-m", "256"]
        - image: seafileltd/seafile-mc:latest
          name: seafile
          env:
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_ROOT_PASSWD
              value: "kodokijo"
            - name: SEAFILE_ADMIN_EMAIL
              value: "admin@protonema.com"
            - name: SEAFILE_ADMIN_PASSWORD
              value: "kodokijo"
            - name: SEAFILE_SERVER_LETSENCRYPT
              value: "false"
            - name: SEAFILE_SERVER_HOSTNAME
              value: "127.0.0.1"
          volumeMounts:
            - name: seafile-data-storage
              mountPath: /shared
      volumes:
        - name: seafile-data-storage
          persistentVolumeClaim:
            claimName: seafile-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: seafile
  namespace: seafile-testing   
spec:
  ports:
    - port: 80
  selector:
    app: seafile
