apiVersion: v1
kind: PersistentVolume
metadata:
  name: seafile-testing-data-pv
  namespace: seafile-testing
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/kube/seafile-testing"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-testing-data
  namespace: seafile-testing
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi	  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile-testing
  namespace: seafile-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seafile
  template:
    metadata:
      labels:
        app: seafile
    spec:
      containers:
        - name: seafile
          image: azizxd/seafile_images
          env:  
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
                secretKeyRef:
                    name: seafile-db-secret
                    key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
                secretKeyRef:
                    name: seafile-db-secret
                    key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
                secretKeyRef:
                    name: seafile-db-secret
                    key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
                secretKeyRef:
                    name: seafile-db-secret
                    key: MYSQL_PASSWORD
          ports:
            - containerPort: 3306
            - containerPort: 8000
            - containerPort: 8082
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: seafile-testing-data
              mountPath: /opt/seafile
      volumes:
        - name: seafile-testing-data
          persistentVolumeClaim:
            claimName: seafile-testing-data
