apiVersion: v1
kind: PersistentVolume
metadata:
  name: seafile-db-pv
  namespace: seafile-testing
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/kube/seafile-db-testing"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-db-pvc
  namespace: seafile-testing
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi	  