apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile-db
  namespace: seafile-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seafile-db
  template:
    metadata:
      labels:
        app: seafile-db
    spec:
      containers:
      - name: seafile-db
        image: mariadb:10.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: kodokijo
        - name: MYSQL_LOG_CONSOLE
          value: "true"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: seafile-db-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: seafile-db-storage
        persistentVolumeClaim:
          claimName: seafile-db-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile-memcached
  namespace: seafile-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seafile-memcached
  template:
    metadata:
      labels:
        app: seafile-memcached
    spec:
      containers:
      - name: seafile-memcached
        image: memcached:1.6.18
        command: ["memcached"]
        args: [-m 256]
        ports:
        - containerPort: 11211
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile
  namespace: seafile-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seafile
  template:
    metadata:
      labels:
        app: seafile
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ["sh", "-c", "until nc -zv seafile-db 3306; do sleep 2; done;"]
      containers:
      - name: seafile
        image: seafileltd/seafile-mc:latest
        env:
        - name: DB_HOST
          value: seafile_db
        - name: DB_ROOT_PASSWD
          value: kodokijo
        - name: TIME_ZONE
          value: Asia/Jakarta
        - name: SEAFILE_ADMIN_EMAIL
          value: admin@mail.co.id
        - name: SEAFILE_ADMIN_PASSWORD
          value: kodokijo
        - name: SEAFILE_SERVER_LETSENCRYPT
          value: "false"
        - name: SEAFILE_SERVER_HOSTNAME
          value: 127.0.0.1:80
        ports:
        - containerPort: 80
        volumeMounts:
            - name: seafile-data-storage
              mountPath: /shared
      volumes:
      - name: seafile-data-storage
        persistentVolumeClaim:
          claimName: seafile-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: seafile-db
  namespace: seafile-testing
spec:
  selector:
    app: seafile-db
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: seafile-memcached
  namespace: seafile-testing
spec:
  selector:
    app: seafile-memcached
  ports:
  - port: 11211
    targetPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: seafile
  namespace: seafile-testing
spec:
  selector:
    app: seafile
  ports:
  - port: 80
    targetPort: 8000
